[tool.pipenv]
include-system-site-packages = false

[tool.isort]
line_length = 79

[tool.black]
line-length = 79
exclude = '''
/(
    \.eggs
  | \.git
  | \.github
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.pyre_configuration
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | pipenv/vendor
  | pipenv/patched
  | tests/pypi
  | tests/test_artifacts
  | get-pipenv.py
  | pyproject.toml
)
'''
parameters = "-S"

[tool.pylint]
init-hook="import os; import sys; abs_path = os.path.abspath(os.path.dirname(__name__)); sys.path.append(os.path.join(abs_path, 'src'))"
extension-pkg-allow-list = ["pyodbc"]
disable = ["unnecessary-lambda-assignment", "consider-using-generator", "too-many-instance-attributes"]
